FROM node:22

WORKDIR /app

RUN mkdir ./backend

COPY ./backend ./backend

RUN cd backend && npm install

RUN cd .. && mkdir ./shared

COPY ./shared/ ./shared

RUN cd ./backend && npm run build

CMD cd ./backend && npm run start:prod