FROM node:22

WORKDIR /app

RUN mkdir ./frontend

COPY ./frontend ./frontend

RUN mkdir ./shared

COPY ./shared ./shared

RUN cd ./frontend && npm i && npm run build:preview

CMD cd ./frontend && npm run preview